# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arithmetic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61rithmetic.proto\x12\nArithmetic\"/\n\x0eRequestMessage\x12\r\n\x05\x66irst\x18\x01 \x01(\x05\x12\x0e\n\x06second\x18\x02 \x01(\x05\"!\n\x0fResponseMessage\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x9d\x01\n\x11\x41rithmeticService\x12@\n\x03\x41\x64\x64\x12\x1a.Arithmetic.RequestMessage\x1a\x1b.Arithmetic.ResponseMessage\"\x00\x12\x46\n\tSubstract\x12\x1a.Arithmetic.RequestMessage\x1a\x1b.Arithmetic.ResponseMessage\"\x00\x42\x16\xaa\x02\x13\x41rithmeticNamespaceb\x06proto3')



_REQUESTMESSAGE = DESCRIPTOR.message_types_by_name['RequestMessage']
_RESPONSEMESSAGE = DESCRIPTOR.message_types_by_name['ResponseMessage']
RequestMessage = _reflection.GeneratedProtocolMessageType('RequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTMESSAGE,
  '__module__' : 'arithmetic_pb2'
  # @@protoc_insertion_point(class_scope:Arithmetic.RequestMessage)
  })
_sym_db.RegisterMessage(RequestMessage)

ResponseMessage = _reflection.GeneratedProtocolMessageType('ResponseMessage', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEMESSAGE,
  '__module__' : 'arithmetic_pb2'
  # @@protoc_insertion_point(class_scope:Arithmetic.ResponseMessage)
  })
_sym_db.RegisterMessage(ResponseMessage)

_ARITHMETICSERVICE = DESCRIPTOR.services_by_name['ArithmeticService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\023ArithmeticNamespace'
  _REQUESTMESSAGE._serialized_start=32
  _REQUESTMESSAGE._serialized_end=79
  _RESPONSEMESSAGE._serialized_start=81
  _RESPONSEMESSAGE._serialized_end=114
  _ARITHMETICSERVICE._serialized_start=117
  _ARITHMETICSERVICE._serialized_end=274
# @@protoc_insertion_point(module_scope)
