# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import arithmetic_pb2 as arithmetic__pb2


class ArithmeticServiceStub(object):
    """인터페이스 정의
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/Arithmetic.ArithmeticService/Add',
                request_serializer=arithmetic__pb2.RequestMessage.SerializeToString,
                response_deserializer=arithmetic__pb2.ResponseMessage.FromString,
                )
        self.Substract = channel.unary_unary(
                '/Arithmetic.ArithmeticService/Substract',
                request_serializer=arithmetic__pb2.RequestMessage.SerializeToString,
                response_deserializer=arithmetic__pb2.ResponseMessage.FromString,
                )


class ArithmeticServiceServicer(object):
    """인터페이스 정의
    """

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Substract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArithmeticServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=arithmetic__pb2.RequestMessage.FromString,
                    response_serializer=arithmetic__pb2.ResponseMessage.SerializeToString,
            ),
            'Substract': grpc.unary_unary_rpc_method_handler(
                    servicer.Substract,
                    request_deserializer=arithmetic__pb2.RequestMessage.FromString,
                    response_serializer=arithmetic__pb2.ResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Arithmetic.ArithmeticService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ArithmeticService(object):
    """인터페이스 정의
    """

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Arithmetic.ArithmeticService/Add',
            arithmetic__pb2.RequestMessage.SerializeToString,
            arithmetic__pb2.ResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Substract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Arithmetic.ArithmeticService/Substract',
            arithmetic__pb2.RequestMessage.SerializeToString,
            arithmetic__pb2.ResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
